import LegalLayout from "@/components/legal/legal-layout";

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Use"
      lastUpdated="August 2, 2026"
      otherDocHref="/privacy"
      otherDocLabel="Privacy Policy"
    >
      <p>
        Welcome to Wayfarer. These Terms of Use ("Terms") govern your access to and use of the
        Wayfarer web application (the "Service"). By creating an account or using the Service,
        you agree to be bound by these Terms. If you do not agree, please do not use the Service.
      </p>

      <h2>1. What Wayfarer Is</h2>
      <p>
        Wayfarer is an AI-powered travel planning tool. It uses artificial intelligence
        (Google Gemini) to generate personalized trip itineraries based on the destination,
        budget, and trip duration you provide. The Service also displays destination photography
        sourced from Unsplash and, where available, real-time flight arrival information sourced
        from AeroDataBox.
      </p>

      <h2>2. AI-Generated Content Is Not Guaranteed Accurate</h2>
      <p>
        Itineraries, budget estimates, flight cost estimates, and other content generated by
        Wayfarer are produced by an AI model and are provided for planning inspiration only. They
        may contain inaccuracies, outdated information, or suggestions that are not feasible in
        practice.
      </p>
      <p>
        <strong>You are responsible for independently verifying</strong> any prices, opening
        hours, visa requirements, flight availability, safety conditions, and other
        travel-critical details before making bookings or travel decisions. Wayfarer is not a
        travel agency and does not book flights, accommodations, or activities on your behalf.
      </p>

      <h2>3. Live Flight Information</h2>
      <p>
        Where shown, "Live Flight Check" data reflects flights that are currently active on a
        given route at the time of your request. It is not a complete flight schedule and should
        not be relied upon for booking decisions. Links to Skyscanner or Google Flights take you
        to third-party websites that are not operated by Wayfarer.
      </p>

      <h2>4. Accounts and Authentication</h2>
      <p>
        You may generate one trip itinerary without an account. Continued use of the itinerary
        generation feature requires signing in with a Google account through Supabase
        Authentication. You are responsible for maintaining the security of your Google account.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use automated tools (bots, scrapers) to access the Service or exceed rate limits</li>
        <li>Attempt to circumvent usage limits, authentication, or security features</li>
        <li>Use the Service to generate content that is unlawful, abusive, or infringing</li>
        <li>Reverse engineer, resell, or misuse the Service or its underlying AI outputs</li>
      </ul>
      <p>
        To protect the Service and keep it available for everyone, requests to our itinerary
        generation, image, and flight-data features are subject to rate limits. We may suspend
        access for accounts or IP addresses that abuse these limits.
      </p>

      <h2>6. Your Content</h2>
      <p>
        Trips, favorite destinations, and preferences you save are stored under your account and
        are visible only to you. You may delete saved trips and favorites at any time from your
        dashboard. Deleting a favorite or trip does not necessarily delete underlying cached
        destination images, which may be reused anonymously to serve other users more
        efficiently.
      </p>

      <h2>7. Third-Party Services</h2>
      <p>
        Wayfarer relies on third-party services to operate, including Google (authentication and
        AI), Supabase (database and authentication infrastructure), Unsplash (photography),
        AeroDataBox (flight data), and Vercel (hosting). Your use of the Service is also subject
        to the applicable terms of these providers where relevant.
      </p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>
        The Service is provided "as is" and "as available" without warranties of any kind, express
        or implied. We do not warrant that the Service will be uninterrupted, error-free, or that
        AI-generated content will be accurate or suitable for your specific travel needs.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, Wayfarer and its developer shall not be liable
        for any indirect, incidental, or consequential damages arising from your use of the
        Service, including but not limited to travel losses, missed flights, or costs incurred
        based on AI-generated recommendations.
      </p>

      <h2>10. Changes to the Service or These Terms</h2>
      <p>
        We may update these Terms or modify, suspend, or discontinue any part of the Service at
        any time. Material changes will be reflected by updating the "Last updated" date above.
        Continued use of the Service after changes constitutes acceptance of the revised Terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these Terms can be sent to{" "}
        <a href="mailto:johnloyduy5@gmail.com">johnloyduy5@gmail.com</a>.
      </p>
    </LegalLayout>
  );
}