// Mapping ng mga destinations papunta sa kanilang pangunahing IATA airport code.
// Hindi lahat ng POPULAR_DESTINATIONS ay may direktang airport — mga walang
// entry dito ay gagamit ng graceful fallback sa UI (walang flight data lang).

export const DESTINATION_AIRPORTS: Record<string, string> = {
  // Philippines
  "Manila, Philippines": "MNL",
  "Cebu, Philippines": "CEB",
  "Davao, Philippines": "DVO",
  "Siargao, Philippines": "IAO",
  "Palawan, Philippines": "PPS",
  "Boracay, Philippines": "MPH",
  "Baguio, Philippines": "MNL",
  "Bohol, Philippines": "TAG",
  "Iloilo, Philippines": "ILO",
  "Zamboanga, Philippines": "ZAM",
  "Camiguin, Philippines": "CGM",
  "Dumaguete, Philippines": "DGT",
  "Subic, Philippines": "CRK",

  // East Asia
  "Tokyo, Japan": "NRT",
  "Osaka, Japan": "KIX",
  "Kyoto, Japan": "KIX",
  "Sapporo, Japan": "CTS",
  "Fukuoka, Japan": "FUK",
  "Okinawa, Japan": "OKA",
  "Nagoya, Japan": "NGO",
  "Hiroshima, Japan": "HIJ",
  "Seoul, South Korea": "ICN",
  "Busan, South Korea": "PUS",
  "Jeju Island, South Korea": "CJU",
  "Incheon, South Korea": "ICN",
  "Beijing, China": "PEK",
  "Shanghai, China": "PVG",
  "Guangzhou, China": "CAN",
  "Shenzhen, China": "SZX",
  "Chengdu, China": "CTU",
  "Xi'an, China": "XIY",
  "Hong Kong": "HKG",
  "Macau": "MFM",
  "Taipei, Taiwan": "TPE",
  "Kaohsiung, Taiwan": "KHH",
  "Ulaanbaatar, Mongolia": "ULN",

  // Southeast Asia
  "Bangkok, Thailand": "BKK",
  "Phuket, Thailand": "HKT",
  "Chiang Mai, Thailand": "CNX",
  "Krabi, Thailand": "KBV",
  "Pattaya, Thailand": "UTP",
  "Koh Samui, Thailand": "USM",
  "Singapore": "SIN",
  "Kuala Lumpur, Malaysia": "KUL",
  "Penang, Malaysia": "PEN",
  "Langkawi, Malaysia": "LGK",
  "Bali, Indonesia": "DPS",
  "Jakarta, Indonesia": "CGK",
  "Yogyakarta, Indonesia": "JOG",
  "Lombok, Indonesia": "LOP",
  "Hanoi, Vietnam": "HAN",
  "Ho Chi Minh City, Vietnam": "SGN",
  "Da Nang, Vietnam": "DAD",
  "Hoi An, Vietnam": "DAD",
  "Ha Long Bay, Vietnam": "HAN",
  "Siem Reap, Cambodia": "REP",
  "Phnom Penh, Cambodia": "PNH",
  "Vientiane, Laos": "VTE",
  "Luang Prabang, Laos": "LPQ",
  "Yangon, Myanmar": "RGN",
  "Bandar Seri Begawan, Brunei": "BWN",

  // South Asia
  "New Delhi, India": "DEL",
  "Mumbai, India": "BOM",
  "Goa, India": "GOI",
  "Jaipur, India": "JAI",
  "Agra, India": "AGR",
  "Bangalore, India": "BLR",
  "Kathmandu, Nepal": "KTM",
  "Colombo, Sri Lanka": "CMB",
  "Male, Maldives": "MLE",
  "Karachi, Pakistan": "KHI",
  "Lahore, Pakistan": "LHE",
  "Islamabad, Pakistan": "ISB",
  "Dhaka, Bangladesh": "DAC",

  // Middle East
  "Dubai, UAE": "DXB",
  "Abu Dhabi, UAE": "AUH",
  "Doha, Qatar": "DOH",
  "Riyadh, Saudi Arabia": "RUH",
  "Jeddah, Saudi Arabia": "JED",
  "Manama, Bahrain": "BAH",
  "Kuwait City, Kuwait": "KWI",
  "Muscat, Oman": "MCT",
  "Amman, Jordan": "AMM",
  "Beirut, Lebanon": "BEY",
  "Tel Aviv, Israel": "TLV",
  "Istanbul, Turkey": "IST",
  "Antalya, Turkey": "AYT",
  "Ankara, Turkey": "ESB",

  // Europe
  "Paris, France": "CDG",
  "Nice, France": "NCE",
  "Lyon, France": "LYS",
  "London, United Kingdom": "LHR",
  "Edinburgh, United Kingdom": "EDI",
  "Manchester, United Kingdom": "MAN",
  "Rome, Italy": "FCO",
  "Milan, Italy": "MXP",
  "Venice, Italy": "VCE",
  "Florence, Italy": "FLR",
  "Naples, Italy": "NAP",
  "Barcelona, Spain": "BCN",
  "Madrid, Spain": "MAD",
  "Seville, Spain": "SVQ",
  "Valencia, Spain": "VLC",
  "Ibiza, Spain": "IBZ",
  "Amsterdam, Netherlands": "AMS",
  "Berlin, Germany": "BER",
  "Munich, Germany": "MUC",
  "Frankfurt, Germany": "FRA",
  "Hamburg, Germany": "HAM",
  "Vienna, Austria": "VIE",
  "Salzburg, Austria": "SZG",
  "Zurich, Switzerland": "ZRH",
  "Geneva, Switzerland": "GVA",
  "Brussels, Belgium": "BRU",
  "Lisbon, Portugal": "LIS",
  "Porto, Portugal": "OPO",
  "Dublin, Ireland": "DUB",
  "Reykjavik, Iceland": "KEF",
  "Oslo, Norway": "OSL",
  "Stockholm, Sweden": "ARN",
  "Copenhagen, Denmark": "CPH",
  "Helsinki, Finland": "HEL",
  "Athens, Greece": "ATH",
  "Santorini, Greece": "JTR",
  "Mykonos, Greece": "JMK",
  "Crete, Greece": "HER",
  "Warsaw, Poland": "WAW",
  "Krakow, Poland": "KRK",
  "Prague, Czech Republic": "PRG",
  "Budapest, Hungary": "BUD",
  "Bucharest, Romania": "OTP",
  "Zagreb, Croatia": "ZAG",
  "Dubrovnik, Croatia": "DBV",
  "Split, Croatia": "SPU",
  "Belgrade, Serbia": "BEG",
  "Vilnius, Lithuania": "VNO",
  "Riga, Latvia": "RIX",
  "Tallinn, Estonia": "TLL",
  "Moscow, Russia": "SVO",
  "Malta": "MLA",

  // North America
  "New York, USA": "JFK",
  "Los Angeles, USA": "LAX",
  "San Francisco, USA": "SFO",
  "Las Vegas, USA": "LAS",
  "Chicago, USA": "ORD",
  "Miami, USA": "MIA",
  "Orlando, USA": "MCO",
  "Seattle, USA": "SEA",
  "Boston, USA": "BOS",
  "Washington D.C., USA": "IAD",
  "Hawaii, USA": "HNL",
  "San Diego, USA": "SAN",
  "Toronto, Canada": "YYZ",
  "Vancouver, Canada": "YVR",
  "Montreal, Canada": "YUL",
  "Mexico City, Mexico": "MEX",
  "Cancun, Mexico": "CUN",
  "Guadalajara, Mexico": "GDL",

  // Central America & Caribbean
  "Havana, Cuba": "HAV",
  "Punta Cana, Dominican Republic": "PUJ",
  "San Juan, Puerto Rico": "SJU",
  "Nassau, Bahamas": "NAS",
  "Kingston, Jamaica": "KIN",
  "Panama City, Panama": "PTY",
  "San Jose, Costa Rica": "SJO",

  // South America
  "Rio de Janeiro, Brazil": "GIG",
  "Sao Paulo, Brazil": "GRU",
  "Buenos Aires, Argentina": "EZE",
  "Santiago, Chile": "SCL",
  "Lima, Peru": "LIM",
  "Cusco, Peru": "CUZ",
  "Bogota, Colombia": "BOG",
  "Cartagena, Colombia": "CTG",
  "Medellin, Colombia": "MDE",
  "Quito, Ecuador": "UIO",

  // Africa
  "Cairo, Egypt": "CAI",
  "Luxor, Egypt": "LXR",
  "Marrakech, Morocco": "RAK",
  "Casablanca, Morocco": "CMN",
  "Cape Town, South Africa": "CPT",
  "Johannesburg, South Africa": "JNB",
  "Nairobi, Kenya": "NBO",
  "Zanzibar, Tanzania": "ZNZ",
  "Kigali, Rwanda": "KGL",
  "Addis Ababa, Ethiopia": "ADD",
  "Lagos, Nigeria": "LOS",
  "Accra, Ghana": "ACC",

  // Oceania
  "Sydney, Australia": "SYD",
  "Melbourne, Australia": "MEL",
  "Brisbane, Australia": "BNE",
  "Perth, Australia": "PER",
  "Gold Coast, Australia": "OOL",
  "Cairns, Australia": "CNS",
  "Auckland, New Zealand": "AKL",
  "Wellington, New Zealand": "WLG",
  "Queenstown, New Zealand": "ZQN",
  "Christchurch, New Zealand": "CHC",
  "Suva, Fiji": "SUV",
  "Nadi, Fiji": "NAN",
};

// Sinusubukan munang exact match, tapos partial match (para sa mga hindi
// pareho ang capitalization o may extra spaces).
export function getAirportCode(destination: string): string | null {
  if (DESTINATION_AIRPORTS[destination]) {
    return DESTINATION_AIRPORTS[destination];
  }

  const normalized = destination.trim().toLowerCase();
  const found = Object.keys(DESTINATION_AIRPORTS).find(
    (key) => key.toLowerCase() === normalized
  );

  return found ? DESTINATION_AIRPORTS[found] : null;
}