export const POPULAR_DESTINATIONS = [
  // Philippines
  "Manila, Philippines",
  "Cebu, Philippines",
  "Davao, Philippines",
  "Siargao, Philippines",
  "Palawan, Philippines",
  "Boracay, Philippines",
  "Baguio, Philippines",
  "Bohol, Philippines",
  "Vigan, Philippines",
  "Batanes, Philippines",
  "Coron, Philippines",
  "El Nido, Philippines",
  "Iloilo, Philippines",
  "Zamboanga, Philippines",
  "Tagaytay, Philippines",
  "Subic, Philippines",
  "La Union, Philippines",
  "Sagada, Philippines",
  "Camiguin, Philippines",
  "Dumaguete, Philippines",

  // East Asia
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Sapporo, Japan",
  "Fukuoka, Japan",
  "Okinawa, Japan",
  "Nagoya, Japan",
  "Hiroshima, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Jeju Island, South Korea",
  "Incheon, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Guangzhou, China",
  "Shenzhen, China",
  "Chengdu, China",
  "Xi'an, China",
  "Hong Kong",
  "Macau",
  "Taipei, Taiwan",
  "Kaohsiung, Taiwan",
  "Ulaanbaatar, Mongolia",
  "Pyongyang, North Korea",

  // Southeast Asia
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Chiang Mai, Thailand",
  "Krabi, Thailand",
  "Pattaya, Thailand",
  "Koh Samui, Thailand",
  "Singapore",
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Langkawi, Malaysia",
  "Malacca, Malaysia",
  "Bali, Indonesia",
  "Jakarta, Indonesia",
  "Yogyakarta, Indonesia",
  "Lombok, Indonesia",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Da Nang, Vietnam",
  "Hoi An, Vietnam",
  "Ha Long Bay, Vietnam",
  "Siem Reap, Cambodia",
  "Phnom Penh, Cambodia",
  "Vientiane, Laos",
  "Luang Prabang, Laos",
  "Yangon, Myanmar",
  "Bandar Seri Begawan, Brunei",
  "Dili, Timor-Leste",

  // South Asia
  "New Delhi, India",
  "Mumbai, India",
  "Goa, India",
  "Jaipur, India",
  "Agra, India",
  "Bangalore, India",
  "Kerala, India",
  "Varanasi, India",
  "Kathmandu, Nepal",
  "Pokhara, Nepal",
  "Colombo, Sri Lanka",
  "Kandy, Sri Lanka",
  "Male, Maldives",
  "Karachi, Pakistan",
  "Lahore, Pakistan",
  "Islamabad, Pakistan",
  "Dhaka, Bangladesh",
  "Thimphu, Bhutan",

  // Middle East
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Mecca, Saudi Arabia",
  "Manama, Bahrain",
  "Kuwait City, Kuwait",
  "Muscat, Oman",
  "Amman, Jordan",
  "Petra, Jordan",
  "Beirut, Lebanon",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Istanbul, Turkey",
  "Cappadocia, Turkey",
  "Antalya, Turkey",
  "Ankara, Turkey",
  "Tehran, Iran",
  "Baghdad, Iraq",

  // Europe
  "Paris, France",
  "Nice, France",
  "Lyon, France",
  "Marseille, France",
  "London, United Kingdom",
  "Edinburgh, United Kingdom",
  "Manchester, United Kingdom",
  "Liverpool, United Kingdom",
  "Rome, Italy",
  "Milan, Italy",
  "Venice, Italy",
  "Florence, Italy",
  "Naples, Italy",
  "Sicily, Italy",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Seville, Spain",
  "Valencia, Spain",
  "Ibiza, Spain",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Hamburg, Germany",
  "Cologne, Germany",
  "Vienna, Austria",
  "Salzburg, Austria",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Interlaken, Switzerland",
  "Brussels, Belgium",
  "Bruges, Belgium",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Dublin, Ireland",
  "Reykjavik, Iceland",
  "Oslo, Norway",
  "Bergen, Norway",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Copenhagen, Denmark",
  "Helsinki, Finland",
  "Athens, Greece",
  "Santorini, Greece",
  "Mykonos, Greece",
  "Crete, Greece",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Zagreb, Croatia",
  "Dubrovnik, Croatia",
  "Split, Croatia",
  "Ljubljana, Slovenia",
  "Belgrade, Serbia",
  "Sarajevo, Bosnia and Herzegovina",
  "Podgorica, Montenegro",
  "Tirana, Albania",
  "Skopje, North Macedonia",
  "Chisinau, Moldova",
  "Kyiv, Ukraine",
  "Lviv, Ukraine",
  "Minsk, Belarus",
  "Vilnius, Lithuania",
  "Riga, Latvia",
  "Tallinn, Estonia",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Malta",
  "Monaco",
  "Andorra la Vella, Andorra",
  "San Marino",
  "Vatican City",
  "Luxembourg City, Luxembourg",

  // North America
  "New York, USA",
  "Los Angeles, USA",
  "San Francisco, USA",
  "Las Vegas, USA",
  "Chicago, USA",
  "Miami, USA",
  "Orlando, USA",
  "Seattle, USA",
  "Boston, USA",
  "Washington D.C., USA",
  "Hawaii, USA",
  "San Diego, USA",
  "New Orleans, USA",
  "Austin, USA",
  "Nashville, USA",
  "Denver, USA",
  "Portland, USA",
  "Philadelphia, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Calgary, Canada",
  "Ottawa, Canada",
  "Quebec City, Canada",
  "Mexico City, Mexico",
  "Cancun, Mexico",
  "Tulum, Mexico",
  "Guadalajara, Mexico",
  "Los Cabos, Mexico",
  "Playa del Carmen, Mexico",

  // Central America & Caribbean
  "Havana, Cuba",
  "Punta Cana, Dominican Republic",
  "San Juan, Puerto Rico",
  "Nassau, Bahamas",
  "Kingston, Jamaica",
  "Montego Bay, Jamaica",
  "Panama City, Panama",
  "San Jose, Costa Rica",
  "Guatemala City, Guatemala",
  "Belize City, Belize",
  "Managua, Nicaragua",
  "San Salvador, El Salvador",
  "Tegucigalpa, Honduras",
  "Bridgetown, Barbados",
  "Aruba",
  "Curacao",

  // South America
  "Rio de Janeiro, Brazil",
  "Sao Paulo, Brazil",
  "Salvador, Brazil",
  "Brasilia, Brazil",
  "Buenos Aires, Argentina",
  "Mendoza, Argentina",
  "Bariloche, Argentina",
  "Santiago, Chile",
  "Valparaiso, Chile",
  "Lima, Peru",
  "Cusco, Peru",
  "Machu Picchu, Peru",
  "Bogota, Colombia",
  "Cartagena, Colombia",
  "Medellin, Colombia",
  "Quito, Ecuador",
  "Galapagos Islands, Ecuador",
  "La Paz, Bolivia",
  "Montevideo, Uruguay",
  "Asuncion, Paraguay",
  "Caracas, Venezuela",
  "Georgetown, Guyana",
  "Paramaribo, Suriname",

  // Africa
  "Cairo, Egypt",
  "Luxor, Egypt",
  "Alexandria, Egypt",
  "Marrakech, Morocco",
  "Casablanca, Morocco",
  "Fez, Morocco",
  "Tunis, Tunisia",
  "Algiers, Algeria",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Durban, South Africa",
  "Nairobi, Kenya",
  "Mombasa, Kenya",
  "Zanzibar, Tanzania",
  "Dar es Salaam, Tanzania",
  "Kilimanjaro, Tanzania",
  "Kampala, Uganda",
  "Kigali, Rwanda",
  "Addis Ababa, Ethiopia",
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Accra, Ghana",
  "Dakar, Senegal",
  "Abidjan, Ivory Coast",
  "Victoria Falls, Zimbabwe",
  "Harare, Zimbabwe",
  "Lusaka, Zambia",
  "Windhoek, Namibia",
  "Gaborone, Botswana",
  "Maputo, Mozambique",
  "Antananarivo, Madagascar",
  "Port Louis, Mauritius",
  "Seychelles",
  "Tripoli, Libya",
  "Khartoum, Sudan",
  "Kinshasa, DR Congo",
  "Yaounde, Cameroon",

  // Oceania
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Gold Coast, Australia",
  "Cairns, Australia",
  "Adelaide, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Queenstown, New Zealand",
  "Christchurch, New Zealand",
  "Suva, Fiji",
  "Nadi, Fiji",
  "Port Moresby, Papua New Guinea",
  "Noumea, New Caledonia",
  "Apia, Samoa",
  "Nuku'alofa, Tonga",
  "Papeete, Tahiti",
  "Honiara, Solomon Islands",
  "Port Vila, Vanuatu",
  "Palau",
];