import jsPDF from "jspdf";
import type { TripResult, TripInput } from "@/types/trip";

export function exportTripToPDF(trip: TripResult, input: TripInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 50;
  const maxWidth = pageWidth - margin * 2;
  let y = 60;

  const addSpace = (amount: number) => {
    y += amount;
    if (y > 760) {
      doc.addPage();
      y = 60;
    }
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  const titleLines = doc.splitTextToSize(trip.title, maxWidth);
  doc.text(titleLines, margin, y);
  addSpace(titleLines.length * 24 + 10);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Personalized itinerary for ${input.destination}`, margin, y);
  addSpace(30);

  // Summary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(20, 150, 170);
  doc.text("Summary", margin, y);
  addSpace(20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(60, 60, 60);
  const cleanSummary = trip.summary.replace(/\*\*/g, "");
  const summaryLines = doc.splitTextToSize(cleanSummary, maxWidth);
  doc.text(summaryLines, margin, y);
  addSpace(summaryLines.length * 14 + 20);

  // Stats
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(20, 20, 20);
  doc.text(`Budget: ${input.budget}`, margin, y);
  doc.text(`Duration: ${input.days} Days`, margin + 180, y);
  if (trip.country) doc.text(`Country: ${trip.country}`, margin + 340, y);
  addSpace(30);

  // Itinerary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(20, 150, 170);
  doc.text("Itinerary", margin, y);
  addSpace(20);

  trip.itinerary.forEach((day, i) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(20, 20, 20);
    const cleanDay = day.replace(/\*\*/g, "");
    const dayLines = doc.splitTextToSize(`${i + 1}. ${cleanDay}`, maxWidth);
    doc.text(dayLines, margin, y);
    addSpace(dayLines.length * 14 + 12);
  });

  // Tips
  if (trip.tips?.length) {
    addSpace(10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(20, 150, 170);
    doc.text("Insights & Tips", margin, y);
    addSpace(20);

    trip.tips.forEach((tip) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(60, 60, 60);
      const cleanTip = tip.replace(/\*\*/g, "");
      const tipLines = doc.splitTextToSize(`• ${cleanTip}`, maxWidth);
      doc.text(tipLines, margin, y);
      addSpace(tipLines.length * 14 + 8);
    });
  }

  // Footer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Wayfarer, powered by Atlas AI", margin, 800);

  const fileName = `${input.destination.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-itinerary.pdf`;
  doc.save(fileName);
}